server:
  port: 10300

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:10200/eureka
    registerWithEureka: true
    fetchRegistry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"