version: "3.8"

services:

  rabbitmq:
    image: rabbitmq:3-management
    mem_limit: 700m
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    networks:
      - bookreservation1


networks:
  bookreservation1:
